# Generated by Django 5.0.4 on 2024-04-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(help_text='Envie apenas imagens', upload_to='uploads/')),
                ('ingresso', models.CharField(choices=[('SISU', 'SISU'), ('VEST', 'Vestibular'), ('PSEN', 'PSEnem')], max_length=4)),
                ('situacao', models.CharField(default='Vinculado', max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=11, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.curso')),
            ],
            options={
                'unique_together': {('nome', 'cpf')},
            },
        ),
    ]
