# Generated by Django 5.0.4 on 2024-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='vinculacao',
            options={'verbose_name_plural': 'Vinculação'},
        ),
        migrations.AlterField(
            model_name='vinculacao',
            name='ingresso',
            field=models.CharField(choices=[('SISU', 'SISU'), ('Vestibular', 'Vestibular'), ('PSEnem', 'PSEnem')], max_length=10),
        ),
    ]
