# Generated by Django 5.0.4 on 2024-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_campus_options_alter_vinculacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacao',
            name='matricula',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
