# Generated by Django 5.0.2 on 2024-04-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_campus_options_alter_vinculacao_options'),
        ('alunos', '0003_alter_vinculacao_matricula'),
    ]

    operations = [
    ]
