# Generated by Django 4.2.11 on 2024-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0005_alter_vinculacao_situacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={"verbose_name_plural": "Curso"},
        ),
        migrations.RenameField(
            model_name="vinculacao",
            old_name="data_nascimento",
            new_name="dataNascimento",
        ),
        migrations.AlterUniqueTogether(
            name="vinculacao",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="campus",
            name="nome",
            field=models.CharField(max_length=50, unique=True, verbose_name="Campus"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nome",
            field=models.CharField(max_length=50, verbose_name="Nome do Curso"),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="cpf",
            field=models.CharField(
                help_text="Dígitos 11 numeros sem traços",
                max_length=11,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="email",
            field=models.EmailField(
                help_text="user@mail.com", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="foto",
            field=models.ImageField(
                help_text="Envie apenas imagens",
                upload_to="uploads/",
                verbose_name="Foto",
            ),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="ingresso",
            field=models.CharField(
                choices=[
                    ("SISU", "SISU"),
                    ("Vestibular", "Vestibular"),
                    ("PSEnem", "PSEnem"),
                ],
                max_length=10,
                verbose_name="Forma de ingresso",
            ),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="matricula",
            field=models.CharField(
                blank=True,
                help_text="Gerada automaticamente",
                max_length=9,
                unique=True,
                verbose_name="Matrícula",
            ),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="nome",
            field=models.CharField(
                help_text="Nome completo", max_length=255, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="vinculacao",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("Vinculado", "Vinculado"),
                    ("Formado", "Formado"),
                    ("Evadido", "Evadido"),
                    ("Jubilado", "Jubilado"),
                ],
                default="Vinculado",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
    ]
