# Generated by Django 4.2.11 on 2024-04-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacao',
            name='dataNascimento',
            field=models.DateField(verbose_name='Data Nascimento'),
        ),
    ]
