# Generated by Django 4.2.11 on 2024-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
