# Generated by Django 4.2.11 on 2024-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_rename_is_staff_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
